### ISSUE TITLE
No Italics

### ISSUE THREAD

**Issue by mkraetke** [motaitalic/vesper-libre#14]
Since I found this font on Google Fonts, I wonder if it's planned to make the Italics open source, too? I would rather live without the medium and heavy weights than without the italics. Unfortunately, a font without italics is in most scenarios not really applicable. In my opinion, more people would use the font if the typical basic styles like bold and italic are available and you can keep “expert” styles or additional character sets for commercial use.

**Comment by fitojb** [comment]
I don’t think italic styles were ever created for this typeface, since it’s a Devanagari-focused project from the start, and in that script italics aren’t really a thing. (I’m aware italicized/slanted fonts exist such as Adobe Devanagari, but my point is that they’re unusual.)

**Comment by motaitalic** [comment]
Hi mkraetke, we've made italics for the Latin already, but not yet for the Devanagari. Vesper was chosen to be included to Google's library primarily because of the Devanagari... and  they didn't seem to have interest in commissioning a matching italic at that time. We'd be happy to add one someday – we agree that italics make designs like this one much more usable. Maybe if more people request this to Google...?

**Comment by mkraetke** [comment]
Hi, thank you much for letting me know. I'll try to request this from Google.
